name: Terraform Plan

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  go-tests:
    name: Run Terratest Integration Tests
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      TF_VAR_client_id: ${{secrets.TF_VAR_client_id}}
      TF_VAR_client_secret: ${{secrets.TF_VAR_client_secret}}
      TF_VAR_subscription_id: ${{secrets.TF_VAR_subscription_id}}
      TF_VAR_tenant_id: ${{secrets.TF_VAR_tenant_id}}


    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 0.12.21
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: ../terratest/
        run: go test -v 