name: Terraform Plan

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=./terraform/ init

      - name: Terraform Format
        run: terraform -chdir=./terraform/ fmt

      - name: Terraform unlock
        run: terraform force-unlock 06dda613-2ba1-7599-fe62-66c24e65877b

      - name: Terraform Plan
        run: terraform -chdir=./terraform/ plan 