name: Terraform Plan

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      TF_VAR_client_id: ${{secrets.TF_VAR_client_id}}
      TF_VAR_client_secret: ${{secrets.TF_VAR_client_secret}}
      TF_VAR_subscription_id: ${{secrets.TF_VAR_subscription_id}}
      TF_VAR_tenant_id: ${{secrets.TF_VAR_tenant_id}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform -chdir=./terraform/ init

      - name: Terraform Format
        run: terraform -chdir=./terraform/ fmt

      - name: Terraform Plan
        run: terraform -chdir=./terraform/ plan