name: Terratest

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  go-tests:
    name: Run Terratest Tests
    runs-on: ubuntu-latest
    environment: production

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      TF_VAR_client_id: ${{secrets.TF_VAR_client_id}}
      TF_VAR_client_secret: ${{secrets.TF_VAR_client_secret}}
      TF_VAR_subscription_id: ${{secrets.TF_VAR_subscription_id}}
      TF_VAR_tenant_id: ${{secrets.TF_VAR_tenant_id}}

    steps:

      - name: Check out code to a GOPATH compatible directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/laszlocph/woodpecker

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Debug
        run: |
          pwd
          echo ${GOPATH}
          echo ${GOROOT}
          export PATH=${PATH}:`go env GOPATH`/bin

      - name: Setup Dependencies
        working-directory: ../terratest/
        run: |
            export PATH=${PATH}:`go env GOPATH`/bin
            go get -v -t -d && go mod tidy

      - name: Test
        working-directory: ../terratest/
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go test -v